name: EPG Guncelleyici

on:
  schedule:
    - cron: '0 6,18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Bota açıkça yazma izni veriyoruz
    permissions:
      contents: write
      
    steps:
      - name: Kodlari cek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutuphaneleri Yukle
        run: pip install requests

      - name: Botu Calistir
        run: python main.py

      - name: EPG Dosyasini Kaydet
        run: |
          git config --global user.name "EPG Bot"
          git config --global user.email "bot@epg.com"
          git add epg.xml
          # Eğer dosya değişmediyse hata vermemesi için "|| exit 0" ekledik
          git commit -m "EPG Guncellendi: $(date)" || exit 0
          git push
