name: EPG Guncelleyici

on:
  schedule:
    - cron: '0 6,18 * * *' # Günde 2 kez (06:00 ve 18:00) otomatik çalışır
  workflow_dispatch: # İstediğin zaman elle çalıştırmanı sağlar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari cek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutuphaneleri Yukle
        run: pip install requests

      - name: Botu Calistir
        run: python main.py

      - name: EPG Dosyasini Kaydet
        run: |
          git config --global user.name "EPG Bot"
          git config --global user.email "bot@epg.com"
          git add epg.xml
          git commit -m "EPG Guncellendi: $(date)"
          git push
